"""Test doubles for external services (OpenAI, sentence-transformers) so the test suite
never needs a real API key or network access to run.

FakeLLMClient implements the exact same public interface as app.services.llm_client.LLMClient
so it can be swapped in via FastAPI's dependency_overrides or passed directly to service
functions that accept an `llm` parameter.
"""

from app.models.enums import ClassificationLabel, MoralFoundation
from app.schemas.analysis import (
    ContentAnalysisSchema,
    NarrativeSummarySchema,
    PrebunkPredictionSchema,
    TruthSandwichSchema,
)


class FakeLLMClient:
    """Deterministic stand-in for LLMClient. Classification is keyword-driven so tests
    can assert on realistic-looking downstream behavior without a live model call."""

    def __init__(self) -> None:
        self.calls: list[tuple[str, tuple, dict]] = []

    async def analyze_content(self, text: str) -> ContentAnalysisSchema:
        self.calls.append(("analyze_content", (text,), {}))
        lowered = text.lower()
        if "hidden tax" in lowered or "secretly" in lowered:
            classification = ClassificationLabel.MISINFORMATION
            outrage = 0.8
        elif "satire" in lowered or "/s" in lowered:
            classification = ClassificationLabel.SATIRE
            outrage = 0.3
        else:
            classification = ClassificationLabel.LEGITIMATE_DEBATE
            outrage = 0.4
        return ContentAnalysisSchema(
            classification=classification,
            confidence=0.9,
            outrage_score=outrage,
            moral_foundation=MoralFoundation.FAIRNESS,
            extracted_claim=text[:200],
            underlying_grievance="fake grievance for testing",
        )

    async def summarize_narrative(self, sample_texts: list[str]) -> NarrativeSummarySchema:
        self.calls.append(("summarize_narrative", (sample_texts,), {}))
        return NarrativeSummarySchema(
            title="Fake Narrative Title",
            summary="Fake narrative summary generated by FakeLLMClient for testing.",
        )

    async def predict_prebunk(
        self, policy_description: str, grounding_context: str
    ) -> PrebunkPredictionSchema:
        self.calls.append(("predict_prebunk", (policy_description, grounding_context), {}))
        return PrebunkPredictionSchema(
            predicted_attack_angle="Fake attack angle: hidden costs",
            likely_framing="Fake framing: government overreach",
            inoculation_explainer="Fake inoculation explainer grounded in test context.",
        )

    async def generate_truth_sandwich(
        self, viral_claim_summary: str, grounding_context: str
    ) -> TruthSandwichSchema:
        self.calls.append(("generate_truth_sandwich", (viral_claim_summary, grounding_context), {}))
        return TruthSandwichSchema(
            core_fact="Fake core fact for testing.",
            nuanced_flag="A claim suggesting otherwise has circulated and is not accurate.",
            reiterated_fact="Fake reiterated fact for testing.",
        )


class AlwaysFailingLLMClient:
    """Simulates LLMNotConfiguredError, for testing the 503 error-translation path."""

    async def analyze_content(self, text: str) -> ContentAnalysisSchema:
        raise self._error()

    async def summarize_narrative(self, sample_texts: list[str]) -> NarrativeSummarySchema:
        raise self._error()

    async def predict_prebunk(
        self, policy_description: str, grounding_context: str
    ) -> PrebunkPredictionSchema:
        raise self._error()

    async def generate_truth_sandwich(
        self, viral_claim_summary: str, grounding_context: str
    ) -> TruthSandwichSchema:
        raise self._error()

    @staticmethod
    def _error() -> Exception:
        from app.services.llm_client import LLMNotConfiguredError

        return LLMNotConfiguredError("fake: no key configured")
